services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3100:3100"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3100
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - DEBUG=TRUE

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - /data/innovation/observe/langfuse_postgres:/var/lib/postgresql/data

  jupyter:
    build: 
      context: ./jupyter
      dockerfile: Dockerfile
    volumes:
      - /data/innovation/observe/juptyer:/app/jupyter      
    ports:
      - 8888:8888
    # environment:
    #   - LANGFUSE_HOST=langfuse-server:3000

# volumes:
#   database_data:
#     driver: local
